#!/usr/bin/python3

import modules.dlconfig as config
import modules.userpass as credentials
import modules.servers as servers
import tabs
import preconfig
import buttonEvent as B

from tkinter import *
from tkinter import ttk
from PIL import Image, ImageTk

setup = config.dlconfigs()

class ipvanishGui():

	def __init__(self, title):
		
		self.ipvanish = Tk()
		self.ipvanish.title(title)
		self.ipvanish.resizable(False,False)
		self.ipvanish.geometry('340x600')
		#tabs.tabLists(self.ipvanish)
		tabs.tabLists.connectButton(self.ipvanish, text = '- Connect -')
				
	def image(self, xplace, yplace, xpos, ypos, width, height, anchor):

		image = ImageTk.PhotoImage(file=setup.create_dirs()[1]+'/assets/ipvanish-text-logo-white.png')
		canvas = Canvas(self.ipvanish, width=width, height=height)
		canvas.image = image
		canvas.create_image(xpos, ypos, anchor=anchor, image=image)
		canvas.place(x=xplace,y=yplace)

	def addStyles(self, widget, height):
			
		style=ttk.Style(self.ipvanish)
		style.configure(style=widget, height=height)
		B.connectScript(self.ipvanish, 15, '- Not Connected -')

	def mainLoop(self):

		self.ipvanish.mainloop()

if __name__ == '__main__':

	preconfig.configuration()
	Ipvanish = ipvanishGui('Ipvanish Gui')
	Ipvanish.image(8, 20, 5, 5, 350, 80, NW)
	Ipvanish.addStyles('TNotebook', 50)
	
	Ipvanish.mainLoop()
